default:
  image: debian-buster-go-builder:v2

# Is performed before the scripts in the stages step
before_script:
  - source /etc/profile
  # Load the ssh private key from the gitlab build variables to enable dupload
  # to connect to the repo via scp
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan repo.stusta.mhn.de >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

# Defines stages which are to be executed
stages:
  - build
  - upload

# Stage "build"
run-build:
  stage: build
  script:
    - apt-get install -y golang-go
    - dpkg-buildpackage -us -uc
    - mkdir build
    - mv ../ocsp-forwarder*.deb build/
    - mv ../ocsp-forwarder*.changes build/
    - mv ../ocsp-forwarder*.tar.gz build/
    - mv ../ocsp-forwarder*.dsc build/
    - mv ../ocsp-forwarder*.buildinfo build/
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

upload:
  stage: upload
  script:
    - echo "Uploading debian package to ssn repository"
    - ssh repo@repo.stusta.mhn.de "echo SSH-Connection working"
    - dupload -f -t ssn_repo build/wumpe*.changes
  when: manual
  only:
    - master

